import { PageHeader } from "@/components/shell/page-header";
import { Panel, PanelHeader, PanelTitle } from "@/components/ui/panel";
import { Badge } from "@/components/ui/badge";
import { api } from "@/lib/api";
import { ProcessGraphCanvas } from "@/components/graph/process-graph";

export default async function GlobalGraphPage() {
  const run = await api.runs.get("run-1");
  return (
    <>
      <PageHeader
        eyebrow="Process Graph"
        title="Visual process maps generated by the AI planner"
        description="Every autonomous run is backed by a directed dependency graph of Oracle Fusion actions, approvals and validation checkpoints."
      />
      <Panel className="overflow-hidden">
        <PanelHeader>
          <PanelTitle>Current reference graph · P2P</PanelTitle>
          <Badge tone="accent">preview</Badge>
        </PanelHeader>
        <div className="h-[680px] w-full">
          <ProcessGraphCanvas graph={run.graph} />
        </div>
      </Panel>
    </>
  );
}
